// Generated from tl-api/db/contentKeys.js — keep the two in step.
//
// These are the strings the components shipped with. ContentContext merges the
// API response over this map, so a failed fetch, a cold API or a key that has
// not been seeded yet still renders real copy instead of empty headings.

export const CONTENT_DEFAULTS = {
  "hero.image": "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=2515&auto=format&fit=crop",
  "hero.image_alt": "Diamond Ring Close up",
  "hero.eyebrow": "Established 2026",
  "hero.title": "The Signature Series",
  "hero.cta": "Shop the Collection",
  "collections.heading": "Latest Arrivals",
  "collections.body": "Discover our curated selection of premium goods, designed for the modern connoisseur.",
  "about.hero_image": "https://images.unsplash.com/photo-1617038224538-2763fcc16382?q=80&w=2000&auto=format&fit=crop",
  "about.hero_image_alt": "Jeweler working",
  "about.hero_title": "The Art of Timelessness",
  "about.hero_eyebrow": "Est. 2026",
  "about.story_image": "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1000&auto=format&fit=crop",
  "about.story_image_alt": "Craftsmanship process",
  "about.story_heading": "Heritage & Quality",
  "about.story_body1": "Founded on the principles of classic elegance and modern sensibility, Tehila Levi is more than a jewelry brand; it is a celebration of enduring beauty. Every piece is a testament to the meticulous art of jewelry making, designed not just for today, but to be cherished for generations.",
  "about.story_body2": "We believe in slow fashion—creating fewer, better things. Our ateliers employ traditional techniques passed down through decades, ensuring that each curve, setting, and polish meets our exacting standards of perfection.",
  "about.pillar1.badge": "01",
  "about.pillar1.title": "Ethically Sourced",
  "about.pillar1.body": "We are committed to using only conflict-free diamonds and recycled precious metals.",
  "about.pillar2.badge": "02",
  "about.pillar2.title": "Hand-Crafted",
  "about.pillar2.body": "Each piece is finished by hand in our Los Angeles studio by master jewelers.",
  "about.pillar3.badge": "03",
  "about.pillar3.title": "Lifetime Warranty",
  "about.pillar3.body": "We stand behind the quality of our jewelry with a comprehensive lifetime guarantee.",
  "contact.heading": "Contact Us",
  "contact.subtitle": "We'd love to hear from you",
  "contact.boutique_heading": "Visit the Boutique",
  "contact.address_line1": "123 Rodeo Drive",
  "contact.address_line2": "Beverly Hills, CA 90210",
  "contact.phone_display": "+1 (310) 555-0123",
  "contact.phone_tel": "+13105550123",
  "contact.map_image": "https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=1000&auto=format&fit=crop",
  "contact.map_image_alt": "Map location",
  "contact.map_label": "View on Google Maps",
  "contact.map_url": "",
  "contact.hours_heading": "Hours",
  "contact.hours1_label": "Monday - Friday",
  "contact.hours1_value": "10am — 7pm",
  "contact.hours2_label": "Saturday",
  "contact.hours2_value": "11am — 5pm",
  "contact.hours3_label": "Sunday",
  "contact.hours3_value": "By Appointment",
  "contact.form_heading": "Bespoke Inquiries",
  "contact.form_label_name": "Name",
  "contact.form_label_email": "Email",
  "contact.form_label_subject": "Subject",
  "contact.form_label_message": "Message",
  "contact.form_submit": "Send Message",
  "contact.form_success": "Thank you for your inquiry. We will respond shortly.",
  "contact.subject1": "General Inquiry",
  "contact.subject2": "Bespoke Commission",
  "contact.subject3": "Private Viewing Appointment",
  "contact.subject4": "Press & Media",
  "footer.brand": "Tehila Levi",
  "footer.rights": "All rights reserved.",
};
